version: 2.0

refrences:
  macos_steps: &steps
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}-{{ arch}}
      - run:
          name: Fetch CocoaPods Specs
          command: |
            if [ "$COCOAPODS_CI_TASKS" != "LINT" ]; then
              master_sha="$(ruby -e "puts '`git submodule status spec/fixtures/spec-repos/master`'.strip.sub(/^-/, '').split(/\s/, 2).first")"
              curl -ssL "https://github.com/CocoaPods/Specs/archive/$master_sha.tar.gz" | tar xz -C spec/fixtures/spec-repos
              git rm spec/fixtures/spec-repos/master
              mv "spec/fixtures/spec-repos/Specs-$master_sha" spec/fixtures/spec-repos/master
              (
                cd spec/fixtures/spec-repos/master
                git init
                git remote add origin https://github.com/CocoaPods/Specs.git
              )
              git submodule update --init
            fi
      - run:
          name: Setup Git
          command: |
            git config --global user.email "tests@cocoapods.org"
            git config --global user.name "CocoaPods Tests"
      - run: bundle exec pod env
      - run: bundle exec rake spec:all

jobs:
  linux-cache:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run: bundle check || bundle install --path .bundle
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - ".bundle"
  macos-cache:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run: bundle check || bundle install --path .bundle
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - ".bundle"

  examples:
    macos:
      xcode: "9.2.0"
    environment:
      BUNDLE_PATH: '$(pwd)/.bundle'
      COCOAPODS_CI_TASKS: EXAMPLES
    <<: *steps

  specs-linux_2.4:
    docker:
      - image: circleci/ruby:2.4
    environment:
      BUNDLE_PATH: '$(pwd)/.bundle'
      COCOAPODS_CI_TASKS: SPECS
    <<: *steps

  specs-macos_system:
    macos:
      xcode: "9.2.0"
    environment:
      BUNDLE_PATH: '$(pwd)/.bundle'
      COCOAPODS_CI_TASKS: SPECS
    <<: *steps

  lint:
    macos:
      xcode: "9.2.0"
    environment:
      BUNDLE_PATH: '$(pwd)/.bundle'
      COCOAPODS_CI_TASKS: LINT
    <<: *steps

  danger:
    docker:
      - image: dantoml/danger
    steps:
      - checkout
      - run: danger

workflows:
  version: 2
  build-test:
    jobs:
      - macos-cache
      - specs-macos_system:
          requires:
            - macos-cache
      - examples:
          requires:
            - macos-cache

      - linux-cache
      - lint:
          requires:
            - linux-cache
      - specs-linux_2.4:
          requires:
            - linux-cache

      - danger

